### ISSUE TITLE
new breaking version with V4

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/gh-php-composer-generate-sbom#3]
V4 of https://github.com/CycloneDX/php-composer will have breaking changes.
This must be addressed here somehow. robably with a major version release here.

**Comment by jkowalleck** [comment]
idea: pin a v3, that requires the composer plugin for version 3.
and then have v4 released ....

**Comment by jkowalleck** [comment]
see https://github.com/CycloneDX/cyclonedx-php-composer/issues/245

**Comment by jkowalleck** [comment]
@coderpatros this needs to be reopene.

The tag `v1` need to be updated to point to the latest revision of this repo.
Please also tag a new `v1.0.1` so that dependency upgrade tools like "renovate" and "dependabot" will bump this gh-actipon for downstream users.

**Comment by coderpatros** [comment]
@jkowalleck I've fixed your access to this project. Do you want to check if you can?

**Comment by jkowalleck** [comment]
@coderpatros orked for me.
was able to add/update the tags :D
